import sqlite3
class table_create:
    def createCursor(dbname):
        con = sqlite3.connect(dbname)
        cur = con.cursor()
        return cur

    def createTables(cur):
        cur.execute("CREATE TABLE admin(ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME TEXT NOT NULL, LAST_NAME TEXT NOT NULL, PHONE_NO INT NOT NULL, ADDRESS TEXT, USERNAME TEXT NOT NULL, PASSWORD TEXT NOT NULL)")
        cur.execute("CREATE TABLE resident(ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME TEXT NOT NULL, LAST_NAME TEXT NOT NULL, PHONE_NO INT NOT NULL, FLAT_NO TEXT NOT NULL, ADDRESS TEXT, USERNAME TEXT NOT NULL, PASSWORD TEXT NOT NULL)")
        cur.execute("CREATE TABLE securitygaurd(ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME TEXT NOT NULL, LAST_NAME TEXT NOT NULL, PHONE_NO INT NOT NULL, CURRENT_ADDRESS TEXT NOT NULL, PERMANENT_ADDRESS TEXT, USERNAME TEXT NOT NULL, PASSWORD TEXT NOT NULL)")
        cur.execute("CREATE TABLE visitor(ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME TEXT NOT NULL, LAST_NAME TEXT NOT NULL, VISIT_PURPOSE TEXT NOT NULL, PHONE_NO INT NOT NULL, VISIT_FLAT TEXT NOT NULL)")
